package com.example.android.pokedexexercise.di;

import android.app.Application;

/**
 * Class extend from Application for adding Dagger
 */
public class BaseApplication extends Application {
    // Interface created that will allow us to inject
    private RetrofitComponent mRetrofitComponent;

    @Override
    public void onCreate() {
        super.onCreate();
        // DaggerRetrofitComponent will be generated by Dagger, when we compile for the first time.
        mRetrofitComponent = DaggerRetrofitComponent
                .builder()
                .retrofitModule(new RetrofitModule())
                .build();
    }

    /**
     *
     * @return the {@link RetrofitComponent} object created for use it in our application at any time.
     */
    public RetrofitComponent getRetrofitComponent() {
        return mRetrofitComponent;
    }
}
